import ExcelJS from "exceljs";
import type { ReportDocument } from "@/lib/reports/types";

function safeCellValue(value: string | number) {
  if (typeof value === "number") return value;
  return /^[\s]*[=+\-@]/.test(value) ? `'${value}` : value;
}

function columnLetter(columnNumber: number) {
  let number = columnNumber;
  let label = "";
  while (number > 0) {
    const remainder = (number - 1) % 26;
    label = String.fromCharCode(65 + remainder) + label;
    number = Math.floor((number - 1) / 26);
  }
  return label;
}

export async function createGradebookWorkbookBlob(
  report: ReportDocument,
  generatedBy: string,
  generatedAt: Date,
) {
  if (report.rows.length === 0) throw new Error("No report data available.");

  const workbook = new ExcelJS.Workbook();
  workbook.creator = generatedBy;
  workbook.created = generatedAt;
  workbook.subject = report.title;
  workbook.title = report.title;

  const gradebook = workbook.addWorksheet("Gradebook", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  gradebook.columns = report.columns.map((header, index) => {
    const longestValue = Math.max(
      header.length,
      ...report.rows.map((row) => String(row[index] ?? "").length),
    );
    return {
      header,
      key: `column${index}`,
      width: Math.min(36, Math.max(12, longestValue + 2)),
    };
  });
  gradebook.addRows(report.rows.map((row) => report.columns.map((_, index) => safeCellValue(row[index] ?? ""))));
  gradebook.autoFilter = {
    from: "A1",
    to: `${columnLetter(report.columns.length)}${report.rows.length + 1}`,
  };
  gradebook.getRow(1).height = 30;
  gradebook.getRow(1).eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF135942" } };
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    cell.border = { bottom: { style: "thin", color: { argb: "FF9AAFA5" } } };
  });

  report.columns.forEach((header, index) => {
    const normalizedHeader = header.toLowerCase();
    gradebook.eachRow((row, rowNumber) => {
      if (rowNumber === 1) return;
      const cell = row.getCell(index + 1);
      cell.alignment = { vertical: "middle", wrapText: true };
      if (rowNumber % 2 === 0) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF4F8F6" } };
      }
      if (["percentage", "normalized"].includes(normalizedHeader) && typeof cell.value === "number") {
        cell.numFmt = '0.0"%"';
      } else if (/cia|midterm|lab|assignment|total|risk score/.test(normalizedHeader) && typeof cell.value === "number") {
        cell.numFmt = "0.0";
      }
      if (normalizedHeader === "risk level") {
        const fillByRisk: Record<string, string> = {
          SAFE: "FFE2F0D9",
          MODERATE: "FFFFF2CC",
          CRITICAL: "FFFCE4D6",
        };
        const fontByRisk: Record<string, string> = {
          SAFE: "FF375623",
          MODERATE: "FF7F6000",
          CRITICAL: "FF9C0006",
        };
        const risk = String(cell.value ?? "").toUpperCase();
        const fill = fillByRisk[risk];
        if (fill) {
          cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: fill } };
          cell.font = { bold: true, color: { argb: fontByRisk[risk] } };
        }
      }
    });
  });

  const summary = workbook.addWorksheet("Summary", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  summary.columns = [
    { header: "Metric", key: "metric", width: 30 },
    { header: "Value", key: "value", width: 34 },
  ];
  summary.addRows([
    ["Report", report.title],
    ["Course", "Database Systems"],
    ["Term", report.period ?? "Current"],
    ["Generated By", generatedBy],
    ["Generated", generatedAt.toLocaleString()],
    ...(report.summary ?? []),
  ].map(([metric, value]) => [safeCellValue(metric), safeCellValue(value)]));
  summary.autoFilter = {
    from: "A1",
    to: `B${summary.rowCount}`,
  };
  summary.getRow(1).eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF135942" } };
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
  });

  const bytes = await workbook.xlsx.writeBuffer();
  return new Blob([bytes], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
}
