import autoTable from "jspdf-autotable";
import { jsPDF } from "jspdf";
import type { ReportDocument } from "@/lib/reports/types";

const PAGE_MARGIN = 14;
const FOOTER_RESERVED = 19;
const CONTENT_TOP = 22;

function columnWidths(report: ReportDocument, availableWidth: number): number[] {
  const weights = report.columns.map((column, index) => {
    const sampleLength = Math.max(
      column.length,
      ...report.rows.slice(0, 20).map((row) => String(row[index] ?? "").length),
    );
    return Math.min(18, Math.max(7, Math.sqrt(sampleLength)));
  });
  const minimum = Math.min(10, availableWidth / report.columns.length);
  const remaining = availableWidth - minimum * report.columns.length;
  const totalWeight = weights.reduce((sum, weight) => sum + weight, 0) || 1;
  return weights.map((weight) => minimum + remaining * (weight / totalWeight));
}

export function buildReportPdf(report: ReportDocument, generatedBy: string, role: string, generatedAt: Date) {
  const pdf = new jsPDF({ orientation: "portrait", format: "a4", unit: "mm" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  const generatedLabel = generatedAt.toLocaleString();

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.setTextColor(20, 75, 58);
  pdf.text("LUMINA AI", PAGE_MARGIN, 16);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(80);
  pdf.text("Academic Intelligence System", PAGE_MARGIN, 22);
  pdf.setDrawColor(180);
  pdf.line(PAGE_MARGIN, 27, pageWidth - PAGE_MARGIN, 27);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.setTextColor(25);
  const titleLines = pdf.splitTextToSize(report.title, contentWidth);
  pdf.text(titleLines, PAGE_MARGIN, 36);
  let cursorY = 36 + titleLines.length * 6;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);
  const details = [
    `Generated by: ${generatedBy} · Role: ${role}`,
    ...(report.filters?.Department ? [`Department: ${report.filters.Department}`] : []),
    ...(report.filters?.Course ? [`Course: ${report.filters.Course}`] : []),
    `Reporting period: ${report.period ?? "Current"} · Generated: ${generatedLabel}`,
  ];
  for (const detail of details) {
    const lines = pdf.splitTextToSize(detail, contentWidth);
    pdf.text(lines, PAGE_MARGIN, cursorY);
    cursorY += lines.length * 3.6;
  }
  cursorY += 2;

  if (report.filters && Object.keys(report.filters).some((key) => key !== "Department" && key !== "Course")) {
    const filterText = `Filters: ${Object.entries(report.filters)
      .filter(([key]) => key !== "Department" && key !== "Course")
      .map(([key, value]) => `${key}=${value}`).join(" · ")}`;
    const lines = pdf.splitTextToSize(filterText, contentWidth);
    pdf.setFontSize(7.5);
    pdf.text(lines, PAGE_MARGIN, cursorY);
    cursorY += lines.length * 3.4 + 2;
  }
  if (report.summary?.length) {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(9);
    pdf.setTextColor(30, 65, 50);
    pdf.text("REPORT SUMMARY", PAGE_MARGIN, cursorY);
    cursorY += 5;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(7.5);
    pdf.setTextColor(40);
    const summaryText = report.summary.map(([label, value]) => `${label}: ${value}`).join("   |   ");
    const summaryLines = pdf.splitTextToSize(summaryText, contentWidth);
    pdf.text(summaryLines, PAGE_MARGIN, cursorY);
    cursorY += summaryLines.length * 3.4 + 3;
  }
  pdf.setDrawColor(210);
  pdf.line(PAGE_MARGIN, Math.min(cursorY, pageHeight - FOOTER_RESERVED - 2), pageWidth - PAGE_MARGIN, Math.min(cursorY, pageHeight - FOOTER_RESERVED - 2));
  cursorY = Math.min(cursorY + 4, pageHeight - FOOTER_RESERVED - 12);

  autoTable(pdf, {
    startY: cursorY,
    head: [report.columns],
    body: report.rows.map((row) => report.columns.map((_, index) => String(row[index] ?? ""))),
    theme: "grid",
    tableWidth: contentWidth,
    margin: { top: CONTENT_TOP, right: PAGE_MARGIN, bottom: FOOTER_RESERVED, left: PAGE_MARGIN },
    columnStyles: Object.fromEntries(columnWidths(report, contentWidth).map((width, index) => [index, { cellWidth: width }])),
    styles: {
      font: "helvetica",
      fontSize: report.columns.length > 9 ? 7 : report.columns.length > 6 ? 7.5 : 8.5,
      cellPadding: 1.5,
      overflow: "linebreak",
      valign: "middle",
      textColor: [35, 45, 40],
      lineColor: [205, 215, 210],
      lineWidth: 0.15,
      minCellHeight: 5,
    },
    headStyles: { fillColor: [19, 89, 66], textColor: 255, fontStyle: "bold", valign: "middle" },
    alternateRowStyles: { fillColor: [242, 247, 245] },
    rowPageBreak: "avoid",
    showHead: "everyPage",
    horizontalPageBreak: false,
    didDrawPage: (data) => {
      if (data.pageNumber === 1) return;
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(8);
      pdf.setTextColor(20, 75, 58);
      pdf.text("LUMINA AI", PAGE_MARGIN, 10);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(75);
      pdf.text(pdf.splitTextToSize(report.title, contentWidth)[0] ?? report.title, PAGE_MARGIN + 25, 10);
      pdf.setDrawColor(190);
      pdf.line(PAGE_MARGIN, 14, pageWidth - PAGE_MARGIN, 14);
    },
  });

  const pageCount = pdf.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    pdf.setPage(page);
    pdf.setDrawColor(170);
    pdf.line(PAGE_MARGIN, pageHeight - 17, pageWidth - PAGE_MARGIN, pageHeight - 17);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(6.5);
    pdf.setTextColor(85);
    pdf.text("Lumina AI · Academic Intelligence System", PAGE_MARGIN, pageHeight - 11);
    pdf.text(`Generated ${generatedLabel}`, pageWidth / 2, pageHeight - 11, { align: "center" });
    pdf.text(`Page ${page} of ${pageCount}`, pageWidth - PAGE_MARGIN, pageHeight - 11, { align: "right" });
    pdf.setFontSize(6);
    pdf.text("CONFIDENTIAL · DEMO REPORT", PAGE_MARGIN, pageHeight - 5);
  }
  return pdf;
}
